export enum StatusOrdemServicoEnum {
    AGUARDANDO_AVALIACAO = 'AGUARDANDO_AVALIACAO',
    EM_AVALIACAO = 'EM_AVALIACAO',
    AGUARDANDO_APROVACAO = 'AGUARDANDO_APROVACAO',
    APROVADA = 'APROVADA',
    REPROVADA = 'REPROVADA',
    EM_EXECUCAO = 'EM_EXECUCAO',
    PRONTA_PARA_RETIRADA = 'PRONTA_PARA_RETIRADA',
    ENTREGUE = 'ENTREGUE',
    CANCELADA = 'CANCELADA',
}